# files are expected to be under config/staches/
# thanks to http://therantsandraves.com/?p=602 for the 'staches

hipster:
  filename: mustache_03.png
  vert_offset: 15
  placement: lip

colonel_mustard:
  filename: colonel_mustard.png
  vert_offset: 40
  mouth_overlap: 100
  placement: lip

hogan:
  filename: mustache_07.png
  vert_offset: 30
  mouth_overlap: 50
  placement: lip

space_helmet:
  filename: SpaceHelmet.png
  vert_offset: 20
  placement: head

paperbag:
  filename: paperbag.png
  vert_offset: 20
  placement: head

visor:
  filename: visor.png
  placement: eyes